### ISSUE TITLE
Adding custom properties to the ErrorHTTP instance does not work

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapbox-error#18]
Adding a custom class like:

```
const err = new ErrorHTTP('hello i am fail', 400);
err.waka = 'flocka';
```

Results in an error object _without_ `waka`. This is a regression from version 2.x

cc @mapbox/maps-api

**Comment by riastrad** [comment]
This issue is quite old, and I don't know that it still holds up: 
![image](https://user-images.githubusercontent.com/16272584/88337814-569ece00-cd05-11ea-9d37-ee3f0effb578.png)
